server:
  port: 8888

spring:
  application:
    name: api-gateway
    cloud:
      gateway:
        routes:
        - id: User Management
          uri: http://localhost:8080
          predicates:
            - Path=/api/user/**
